# Generated by Django 4.2 on 2023-05-01 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(choices=[], through='portal.PostCategory', to='portal.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 1, 6, 6, 54, 255909)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 1, 6, 6, 54, 251261)),
        ),
    ]
