# Generated by Django 4.2 on 2023-05-01 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_author_user_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 13, 38, 58, 378085)),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(choices=[(1, 'Наука и технологии'), (2, 'Культура'), (3, 'Политика'), (4, 'Происшествия'), (5, 'Спорт'), (6, 'Религия'), (7, 'Экономика')], through='portal.PostCategory', to='portal.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 1, 13, 38, 58, 373795)),
        ),
    ]
